#!/usr/bin/php -q
<?php
require 'vendor/autoload.php';
use Camspiers\JsonPretty\JsonPretty;

# CLI
$opcion = $argv[1]; # Convertir a uppercase, validar placa!

# actualizar
if($opcion == 'actualizar') {
    require 'actualizar.php';
    print 'verificentros.json actualizado!' . PHP_EOL;
}
# placas
if(strlen($opcion) == 6) {
	$placas = strtoupper($opcion);
    require 'consulta_placas.php';
    var_dump($consulta) . PHP_EOL;
}
?>
